version: '3.8'

services:
  client-gateway:
    image: client-gateway:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - .:/app
    networks:
      - client-network
